apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: spring-boot-app
  name: postgres-tcnp
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "tuto-obs.selectorLabels" . | nindent 6}}
  policyTypes:
  - Ingress
  - Egress
