apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-actuator-monitor
  labels:
    app: spring-boot-app
spec:
  selector:
    matchLabels:
      {{- include "tuto-obs.selectorLabels" . | nindent 6}}
  endpoints:
    - port: http  
      path: /actuator/prometheus
      interval: 30s